---
title: "Kanjera South Figures"
author: "Jonathan Reeves"
date: "2/1/2021"
output: pdf_document
---

```{r step up, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)


tiff_figures = TRUE

library(ggplot2)
library(grid)
library(gridExtra)
library(dplyr)
library(dunn.test)
library(raster)
library(ggplot2)
library(ggsn)
library(ggrepel)
library(sf)
library(ggnewscale)
library(knitr)

```

```{r table 1}

rm <- read.csv("Data/Raw_mats.csv")

kable(rm,align = "c",caption = "A list of rock types included in this analysis",col.names = c("Raw Material","Abreviation", "Origin", "Provenance"
                                                                                              ))


```


```{r cores prep}
cores <- read.csv("Data/kjs_cores.csv", stringsAsFactors = FALSE)
cores$DeLaTorre.Typology[cores$DeLaTorre.Typology == "multifacial irregular "] <- "multifacial irregular"
cores$DeLaTorre.Typology[cores$DeLaTorre.Typology == "unidirectional abrupt bipolar " ] <- "unidirectional abrupt bipolar"
cores$RM <- toupper(cores$RM)

cores$DeLaTorre.Typology <- ordered(cores$DeLaTorre.Typology, 
                                   levels = c("unifacial simple partial",
                                              "unidirectional abrupt unipolar",
                                              "unidirectional abrupt bipolar",
                                              "bidirectional abrupt",
                                              "bifacial partial",
                                              "unifacial centripetal",
                                              "bifacial centripetal",
                                              "polyhedral",
                                              "multifacial irregular"))
                                              
                                              
                                              
   

## Reorder factor levels


cores$rm.provenance <- "Distant"
cores$rm.provenance[cores$RM %in% c("HLI", "FNY", "HPH")] <- "Local"
cores$RM <- factor(cores$RM, levels = c("BBA", "BFE", "BQU", "NYR","OGR", "NYC", "HLI", "HPH", "FNY"))

cores_table <- cores %>% 
   group_by(RM) %>%
   dplyr::summarise("N" = dplyr::n(),
              "Avg. Length" = round(mean(Axis1),2),
              "Avg. Width" = round(mean(Axis2),2),
              "Avg. Thick" = round(mean(Axis3),2),
              "Avg. Mass (g)" = round(mean(Mass),3),
              "Avg. N flake scars" = round(mean(FlakScars, na.rm = TRUE)), 
              "Avg. Exploitation Surfaces" = round(mean(ExploitationSurfaces, na.rm = TRUE)),
              "Avg. Surface Interactions" = round(mean(Interactions, na.rm = TRUE)),
              "Avg. % Mass Lost" = round(mean(fixedpredict * 100)))

kable(cores_table,caption = "A Summary of the cores included in the analysis by raw material")

```

```{r flake prep}

flakes <- read.csv("Data/kjs_flakes.csv")
flakes$Raw.Material <- factor(toupper(flakes$Raw.Material), levels = c("BBA", "BFE", "BQU", "NYR","OGR", "NYC", "HLI", "HPH", "FNY"))
flakes$rm.provenance <- "Distant"
flakes$rm.provenance[flakes$Raw.Material %in% c("HLI", "FNY", "HPH")] <- "Local"

flakes_table <- flakes %>% dplyr::group_by(Raw.Material) %>%
   dplyr::summarise("N" = dplyr::n(),
                    "Avg. Length" = round(mean(Length),2),
                    "Avg. Width" = round(mean(Length),2),
                    "Avg. Mass (g)" = round(mean(Mass),3),
                    "Avg. N of platform facets" = round(mean(Platform.facets)),
                    "Avg. N of dorsal scars" = round(mean(N.Flake.Scars)), 
                    "Avg. N of scar dir" = round(mean(Flake.scar.direction)),
                    "Avg. percent cortex" = round(mean(Percent.Cortex),2),
                    "Avg. Flake Seq" = round(mean(flake.seq))
)

flakes_table <- flakes_table %>% rename(RM = Raw.Material)
kable(flakes_table, caption = "A Summary of flakes included in the Study by raw material")
```


```{r fig-1, fig.height=5, fig.width=7, fig.cap= "A map of the Homa Peninsula. Kanjera South is situated to the East of Homa Mountain. The Homa Mountain carbonatite center is the primary source of the local raw materials including Homa limestone (HLi), Homa Phonolite (HPh), and Fenetized nyanzian rocks (FNy). Drainages coming off the flanks of Homa Mountain carry these local rock types to within the immediate vicinity of Kanjera South. Distant or exotic raw materials originate in river conglomerates much farther to the east of the Samanga Fault. These include Bukoban andesite (BBa), Bukoban felsite (BFe), Bukoban quartzite (BQu), Nyanzian rhyolite (NyR), and Oygus granite (OGr)  \\label{map}" }


dem <- raster("Figures/Figure_data/Homa_Penninsula_DEM_30m2.tif")

dem[dem$Homa_Penninsula_DEM_30m2 <= 1134] <- NA
slope <- raster::terrain(dem, opt = "slope")
aspect <- terrain(dem, opt = "aspect")
dem <- data.frame(rasterToPoints(dem))
hs <- hillShade(slope = slope,
                aspect = aspect,
                angle = 50,
                direction = 315,
                normalize = TRUE)

hs <- data.frame(rasterToPoints(hs))

water <- read_sf("Figures/Figure_data/ke_major-rivers.shp")
kjs <- read_sf("Figures/Figure_data/KJS_WSG_84.shp")
rivers2<-read_sf("Figures/Figure_data/Rivers_homa_WGS2.shp")
fault <- read_sf("Figures/Figure_data/SamangaFault_WGS.shp")
st_geometry(kjs) <- NULL

ggplot()+
   geom_raster(data = hs,aes(x=x, y=y, fill = layer),show.legend = FALSE)+
   scale_fill_gradientn(colours = grey.colors(100,start = .5, end = 0))+
   new_scale_fill()+
   
   geom_raster(data = dem[dem$Homa_Penninsula_DEM_30m2 > 1134 & dem$Homa_Penninsula_DEM_30m2 < 2000,],
               aes(x=x,y=y,fill = Homa_Penninsula_DEM_30m2),alpha = .4, inherit.aes = FALSE)+
 
  geom_sf(data = rivers2, color = "dodger blue2", alpha = .5)+
  geom_sf(data = fault,linetype =2) +
  geom_sf_text(data = fault, aes(label = "Samanga Fault"), angle = 47, nudge_y = -.015)+ 
   scale_fill_gradientn(colours = terrain.colors(100), "Elevation (m)")+
  geom_point(data = kjs, aes(x= X, y = Y)) +
  geom_label_repel(data= kjs, aes(x = X, y = Y,label = Local),
                  box.padding   = 1, 
                  point.padding = .5,
                  segment.color = 'black',
                  color = "black")+
   
   north(location = "bottomleft", symbol = 10, x.min = 34.43,x.max = 34.9, y.min = -0.525, y.max = -.27195)+
   scalebar(location = "bottomleft",dist_unit = "km",dist = 4, x.min = 34.44,x.max = 34.9, y.min = -0.528, y.max = -.275, 
            transform = TRUE,st.dist = .025) + 
   
   scale_x_continuous(limits = c(34.42,34.8), expand = c(0,0))+
   scale_y_continuous(limits = c(-0.55,-.275), expand = c(0,0))+
   theme(panel.background = element_rect(fill = "dodger blue1"),
         panel.grid = element_blank(),
         panel.spacing = unit(1, "cm"),
         axis.text = element_blank(),
         axis.title = element_blank(),
         axis.ticks = element_blank())


```


```{r fig-2, echo=FALSE, warning=FALSE, , fig.cap="Examples of thestone artifacts found at Kanjera South. (A) Core produced on Homa limestone. (B) Core produced on Oyugis granite. (C) Core produced on Bukoban quartzite. (D) Core produced on Fenetized nyanzian.  \\label{tools}", paged.print=FALSE}

library(png)
library(grid)

  figure_03 = readPNG("Figures/KJS_Lithics_Fig_PNG.png")
  g <- rasterGrob(figure_03, interpolate=TRUE)
  ggplot(NULL, aes(NULL, NULL)) + geom_blank() + xlab('') + ylab('') +
    annotation_custom(g, xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf)+
    theme(panel.background = element_blank())
```


```{r fig-3, echo = FALSE, warnings=FALSE, dpi= 1000,fig.height= 3, fig.width= 6, fig.cap= "The distribution of core reduction intensity values as predicted by the GLMM (Douglass et al 2018). The results show stark differences in the degree of reduction in materials originating from more distant sources than those that originate from local sources of stone. \\label{core_redux_rm}"}

a <- ggplot(cores, aes(x = RM, y = fixedpredict, fill = rm.provenance)) + 
   geom_boxplot(show.legend = FALSE) + 
   scale_fill_manual(values = c("#E69F00", "#56B4E9"))+
   scale_y_continuous(limits = c(0,1))+
   labs(x = "Raw Material", y = "Reduction intensity (% Mass Lost)") +
   theme(panel.background = element_rect(color = "black", fill = "white"))


b <- ggplot(cores, aes(x = rm.provenance, y = fixedpredict, fill = rm.provenance)) + 
   geom_boxplot(show.legend = FALSE) + 
   scale_fill_manual(values = c("#E69F00", "#56B4E9"))+
   scale_y_continuous(limits = c(0,1))+
   labs(x = "Raw Material Provenance", y = "Reduction intensity (% Mass Lost)")+
   theme(panel.background = element_rect(color = "black", fill = "white"))


   
grid.arrange(a,b, ncol = 2)

```



```{r}
res <- wilcox.test(cores$fixedpredict~cores$rm.provenance)
```

```{r fig-4, fig.height=3, fig.width=5, warning=FALSE, echo=FALSE, fig.cap= "The distribution of flake sequence values present within the Kanjera South flake assemblage. As is the case with the core assemblage, the primary differences in flake sequence values are between materials originating from more distant sources than those that originate from local sources of stone. \\label{flake_seq_rm}"}

  ggplot(flakes, aes(x = Raw.Material, y = flake.seq, fill = rm.provenance)) + 
   geom_boxplot()+
   scale_fill_manual(values = c("#E69F00", "#56B4E9"))+
   labs(x = "Raw Material", y = "Flake Sequence")+
   guides(fill=guide_legend(title="Raw Material Provenance")) +
   theme(panel.background = element_rect(color = "black", fill = "white"),
         legend.position = "right")
```

```{r}
res <- wilcox.test(flakes$flake.seq~
             flakes$rm.provenance)
```


```{r fig-5,echo = FALSE, fig.width=6.5, fig.height= 4, fig.cap= "Left: The distribution of core reduction strategies by raw material type. With the exception of Homa Limestone, raw materials that derive from the Kisi highlights more greatly represented by complex core reduction strategies than those that can be found in the immediate vicinity of Kanjera South. Right: The distribution of reduction intensity values according to reduction strategy.  **USP**: Unifacial Simple Partial. **UAU**: Unidirectional abrupt unifacial. **UABI**: Unifacial abrupt bidirectional. **BA**: Bidirectional Abrupt. **BAP** Bifacial Partial. **UC**: Unifacial centripetal. **BC**: Bifacial Centripetal. **Poly**: Polyhedral. **MFI**: Mutifacial Irregular. The colors of the boxplots correspond with the representation of different reduction strategies in the left figure. \\label{core.tech}"}



redux.tech<-ggplot(cores, aes(x = DeLaTorre.Typology, y = fixedpredict, fill = DeLaTorre.Typology)) +
   geom_boxplot() +
   scale_fill_brewer(type = "div", palette = 6, direction = -1) + 
      labs(x = "Core Reduction Strategy", y = "Reduction intensity (% Mass Lost)")+
      guides(fill=guide_legend(title="Provenance")) +
   scale_x_discrete(labels= c("USP", "UAU", "UABI", "BA", "BAP", "UC", "BC","Poly", "MFI"))+
   theme(panel.background = element_rect(color = "black", fill = "white"),
         legend.position = "none",
         axis.text.x = element_text(vjust = 1, hjust = 1, angle = 70))


rm.tech <- ggplot(cores, aes(x =RM , fill = DeLaTorre.Typology)) +
   geom_bar(position = "fill") +
      scale_fill_brewer(type = "div", palette = 6, direction = -1) + 
   labs(x = "Raw Material", y = "Relative Frequency") + 
   theme(panel.background = element_rect(color = "black", fill = "white"),
         legend.position = "none")

grid.arrange(rm.tech, redux.tech,ncol=2)


redux.strat.table <- table(cores$RM,cores$DeLaTorre.Typology)

```

```{r fig-6, echo=FALSE,dpi= 1000,fig.height= 3, fig.width= 6, fig.cap= " Left: Boxplots of the measures of flake efficiency. Y-axis represents perimeter of flakes divided by a logarithmically transformed mass value. Right: A scatter plot examining the relationship between flake efficiency and flake sequence. \\label{flake_efficiency}"}

allflakes<-read.csv("Data/PerMass_AllFlakes.csv")
allflakes$RM <- factor(allflakes$RM, levels = c("BFe", "NYr", "BBA","BQu","HLi","FNy"), ordered = TRUE)

flakes <- left_join(flakes,allflakes[,c("Accession", "PerMass")], by = c("ID" = "Accession"))

flakes$rm.provenance <- "Distant"
flakes$rm.provenance[flakes$Raw.Material %in% c("HLI", "FNY", "HPH")] <- "Local"

allflakes$rm.provenance<-"Distant"
allflakes$rm.provenance[allflakes$RM %in% c("HLi","FNy")]<-"Local"

Plot1<-ggplot(data=allflakes, aes(x=RM, y=PerMass, fill=rm.provenance))+
  geom_jitter()+
  scale_fill_manual(values = c("#E69F00", "#56B4E9"))+
  theme_classic()+
   theme(legend.position = "top")


Plot2<-Plot1+
  geom_violin()+
  ylab("Edge to Mass Ratio mm/log(grams)")+
  labs(fill = "Raw Material Provenance")+
  xlab("Raw Materials")

Plot3 <- ggplot(flakes, aes(x = flake.seq, y = PerMass, color = rm.provenance))+
   geom_point()+
   scale_color_manual(values = c("#E69F00", "#56B4E9"))+
   ylab("Edge to Mass Ratio mm/log(grams)")+
   xlab("Flake Sequence")+
   theme_classic()+
   theme(legend.position = "none")


grid.arrange(Plot2, Plot3, ncol =2)


```

```{r}
kruskal.res <- kruskal.test(cores$fixedpredict, cores$DeLaTorre.Typology)
#kruskal.res
```

```{r}

cores.table <- table(cores$rm.provenance,cores$DeLaTorre.Typology)
#kable(cores.table)

```

```{r}

res <- fisher.test(cores.table, simulate.p.value = TRUE)

```
